// <auto-generated />
using System;
using Bookmaster.Modules.Books.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookmaster.Modules.Books.Infrastructure.Database.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20250617134653_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("books")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("authors_id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.HasKey("AuthorsId", "BookId")
                        .HasName("pk_book_authors");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_book_authors_book_id");

                    b.ToTable("book_authors", "books");
                });

            modelBuilder.Entity("BookBookCategory", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_id");

                    b.HasKey("BookId", "CategoriesId")
                        .HasName("pk_book_book_categories");

                    b.HasIndex("CategoriesId")
                        .HasDatabaseName("ix_book_book_categories_categories_id");

                    b.ToTable("book_book_categories", "books");
                });

            modelBuilder.Entity("Bookmaster.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "books");
                });

            modelBuilder.Entity("Bookmaster.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "books");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Books.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.ToTable("authors", "books");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GoogleBookId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_book_id");

                    b.Property<string>("GoogleBookInfoLink")
                        .HasColumnType("text")
                        .HasColumnName("google_book_info_link");

                    b.Property<string>("GoogleBookPreviewLink")
                        .HasColumnType("text")
                        .HasColumnName("google_book_preview_link");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<string>("PrintType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("print_type");

                    b.Property<string>("PublishedDate")
                        .HasColumnType("text")
                        .HasColumnName("published_date");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<string>("Subtitle")
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", "books");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Books.BookCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_book_categories");

                    b.ToTable("book_categories", "books");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Library.LibraryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_library_entries");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_library_entries_book_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_library_entries_person_id");

                    b.ToTable("library_entries", "books");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_people_identity_id");

                    b.ToTable("people", "books");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", "books");
                });

            modelBuilder.Entity("LibraryEntryTag", b =>
                {
                    b.Property<Guid>("LibraryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_entry_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.HasKey("LibraryEntryId", "TagsId")
                        .HasName("pk_library_entry_tags");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_library_entry_tags_tags_id");

                    b.ToTable("library_entry_tags", "books");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Bookmaster.Modules.Books.Domain.Books.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_authors_authors_authors_id");

                    b.HasOne("Bookmaster.Modules.Books.Domain.Books.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_authors_books_book_id");
                });

            modelBuilder.Entity("BookBookCategory", b =>
                {
                    b.HasOne("Bookmaster.Modules.Books.Domain.Books.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_book_categories_books_book_id");

                    b.HasOne("Bookmaster.Modules.Books.Domain.Books.BookCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_book_categories_book_categories_categories_id");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Library.LibraryEntry", b =>
                {
                    b.HasOne("Bookmaster.Modules.Books.Domain.Books.Book", "Book")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_library_entries_books_book_id");

                    b.HasOne("Bookmaster.Modules.Books.Domain.People.Person", "Person")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_library_entries_people_person_id");

                    b.Navigation("Book");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LibraryEntryTag", b =>
                {
                    b.HasOne("Bookmaster.Modules.Books.Domain.Library.LibraryEntry", null)
                        .WithMany()
                        .HasForeignKey("LibraryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_library_entry_tags_library_entries_library_entry_id");

                    b.HasOne("Bookmaster.Modules.Books.Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_library_entry_tags_tags_tags_id");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.Books.Book", b =>
                {
                    b.Navigation("LibraryEntries");
                });

            modelBuilder.Entity("Bookmaster.Modules.Books.Domain.People.Person", b =>
                {
                    b.Navigation("LibraryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
