// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bookmaster.Modules.Books.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Book_Categories : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "name",
                schema: "books",
                table: "authors",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.CreateTable(
                name: "book_categories",
                schema: "books",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_book_categories", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "book_book_categories",
                schema: "books",
                columns: table => new
                {
                    book_id = table.Column<Guid>(type: "uuid", nullable: false),
                    categories_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_book_book_categories", x => new { x.book_id, x.categories_id });
                    table.ForeignKey(
                        name: "fk_book_book_categories_book_categories_categories_id",
                        column: x => x.categories_id,
                        principalSchema: "books",
                        principalTable: "book_categories",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_book_book_categories_books_book_id",
                        column: x => x.book_id,
                        principalSchema: "books",
                        principalTable: "books",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_book_book_categories_categories_id",
                schema: "books",
                table: "book_book_categories",
                column: "categories_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "book_book_categories",
                schema: "books");

            migrationBuilder.DropTable(
                name: "book_categories",
                schema: "books");

            migrationBuilder.AlterColumn<string>(
                name: "name",
                schema: "books",
                table: "authors",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(500)",
                oldMaxLength: 500);
        }
    }
}
