// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Bookmaster.Modules.Books.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Book_Updates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "small_thumbnail",
                schema: "books",
                table: "books");

            migrationBuilder.RenameColumn(
                name: "text_snippet",
                schema: "books",
                table: "books",
                newName: "google_book_preview_link");

            migrationBuilder.AddColumn<string>(
                name: "language",
                schema: "books",
                table: "books",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "print_type",
                schema: "books",
                table: "books",
                type: "text",
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "language",
                schema: "books",
                table: "books");

            migrationBuilder.DropColumn(
                name: "print_type",
                schema: "books",
                table: "books");

            migrationBuilder.RenameColumn(
                name: "google_book_preview_link",
                schema: "books",
                table: "books",
                newName: "text_snippet");

            migrationBuilder.AddColumn<string>(
                name: "small_thumbnail",
                schema: "books",
                table: "books",
                type: "text",
                nullable: true);
        }
    }
}
